import Foundation

/// Top-level snapshot written by the main app and consumed by the widget extension.
///
/// Schema v1 (frozen).
/// - Encoded with `JSONEncoder` and `dateEncodingStrategy = .iso8601`.
/// - `version` is bumped only on breaking shape changes; widget should refuse
///   unknown versions and fall back to a placeholder until refreshed.
///
/// Design notes:
/// - `ProviderSnapshot.usedPercent` (carried inside `windows`) is the great
///   common-denominator field across all billing models — the widget renders
///   ring/bar progress directly from it.
/// - `windows` is an array (not a flat struct) because Claude (5h+7d), Codex
///   (primary+secondary), Z.ai (token+mcp) are all multi-window.
/// - The Small widget family renders only `primaryWindowId`; Medium/Large can
///   walk `windows` if needed in later milestones.
/// - `kind = .quota` → progress bar; `kind = .usage` → big spend amount.
///   This lets the widget branch on shape without inspecting each provider's
///   internal naming.
struct WidgetSnapshot: Codable, Equatable {
    /// Schema version. Increment on breaking changes.
    let version: Int // fixed 1

    /// When this snapshot was generated by the main app.
    let snapshotAt: Date

    /// All provider snapshots in display order (sorted by usedPercent desc).
    let providers: [ProviderSnapshot]

    /// Total monthly API cost, USD and optional RMB.
    let monthlyCost: MonthlyCost?
}

/// Single provider's snapshot for widget rendering.
struct ProviderSnapshot: Codable, Equatable {
    /// Stable id matching `ProviderIdentifier.rawValue`.
    let id: String

    /// Human-readable display name.
    let displayName: String

    /// Compact brand name for space-constrained widget headers. Optional so
    /// existing v1 snapshots continue to decode without migration.
    let compactDisplayName: String?

    /// Determines rendering style: progress bar vs spend amount.
    let kind: Kind

    /// Which window in `windows` is the primary (Small family renders this).
    /// Nil if `windows` is empty.
    let primaryWindowId: String?

    /// Quota/usage windows. May be empty for usage-only providers.
    let windows: [UsageWindow]

    /// Only for `.usage` kind: cost in USD.
    let spendUSD: Double?

    /// When the provider was actually fetched (may be earlier than snapshotAt).
    let fetchedAt: Date?

    /// Availability of the provider data itself. This is deliberately
    /// independent from quota severity so the widget never presents cached or
    /// unavailable data as a fresh quota.
    let status: WidgetDataStatus?

    /// Optional per-account data. Present only for providers that expose a
    /// stable account-level quota presentation, currently Codex.
    let accounts: [ProviderAccountSnapshot]?

    init(
        id: String,
        displayName: String,
        compactDisplayName: String? = nil,
        kind: Kind,
        primaryWindowId: String?,
        windows: [UsageWindow],
        spendUSD: Double?,
        fetchedAt: Date?,
        status: WidgetDataStatus? = nil,
        accounts: [ProviderAccountSnapshot]? = nil
    ) {
        self.id = id
        self.displayName = displayName
        self.compactDisplayName = compactDisplayName
        self.kind = kind
        self.primaryWindowId = primaryWindowId
        self.windows = windows
        self.spendUSD = spendUSD
        self.fetchedAt = fetchedAt
        self.status = status
        self.accounts = accounts
    }

    enum Kind: String, Codable, Equatable {
        /// Quota-based: progress bar driven by `usedPercent`.
        case quota
        /// Pay-as-you-go: spend amount in `spendUSD`.
        case usage
    }
}

/// Provider-level freshness and availability for generic widgets.
/// Optional on `ProviderSnapshot` for backwards-compatible decoding of v1
/// snapshots written before this field existed.
enum WidgetDataStatus: String, Codable, Equatable {
    case available
    case stale
    case unavailable
}

/// Single quota window within a provider (e.g. "5h", "7d", "monthly").
struct UsageWindow: Codable, Equatable {
    /// Stable id: "5h" / "7d" / "monthly" / "token" / "mcp" / "primary" / "secondary".
    let id: String

    /// UI display label.
    let label: String

    /// 0-100+. Drives widget ring/bar rendering.
    let usedPercent: Double

    /// When this window resets.
    let resetsAt: Date?

    /// Absolute used value (quota-based only).
    let used: Int?

    /// Absolute limit value (quota-based only).
    let limit: Int?

    /// Window duration in seconds, when the provider exposes it.
    let windowSeconds: Int?

    /// Stable display priority. Lower values render first.
    let priority: Int?

    init(
        id: String,
        label: String,
        usedPercent: Double,
        resetsAt: Date?,
        used: Int?,
        limit: Int?,
        windowSeconds: Int? = nil,
        priority: Int? = nil
    ) {
        self.id = id
        self.label = label
        self.usedPercent = usedPercent
        self.resetsAt = resetsAt
        self.used = used
        self.limit = limit
        self.windowSeconds = windowSeconds
        self.priority = priority
    }
}

/// Codex account data safe for crossing the app/widget process boundary.
struct ProviderAccountSnapshot: Codable, Equatable {
    /// Stable opaque id. Raw account identifiers and email addresses never
    /// enter the snapshot through this field.
    let id: String

    /// Masked account label suitable for the widget configuration picker.
    let displayName: String

    /// Subscription plan label, when available.
    let plan: String?

    /// Account availability independent from quota severity.
    let status: ProviderAccountStatus

    /// Base Codex quota windows in display priority order.
    let metrics: [UsageWindow]

    /// Last successful fetch time, when known.
    let fetchedAt: Date?
}

enum ProviderAccountStatus: String, Codable, Equatable {
    case available
    case stale
    case unavailable
}

/// Monthly cost summary.
struct MonthlyCost: Codable, Equatable {
    /// USD amount. Display layer formats to 2 decimals.
    let usd: Double

    /// RMB amount (optional, requires exchange rate).
    let rmb: Double?
}

// MARK: - Content equality (ignores heartbeat timestamps)

extension WidgetSnapshot {
    /// Compare semantic content, ignoring `snapshotAt` heartbeat updates.
    /// Used to decide whether a fresh disk write should trigger `reloadTimelines`.
    func isContentEqual(to other: WidgetSnapshot) -> Bool {
        monthlyCost == other.monthlyCost &&
        providers.count == other.providers.count &&
        zip(providers, other.providers).allSatisfy { $0.isContentEqual(to: $1) }
    }
}

extension ProviderSnapshot {
    func isContentEqual(to other: ProviderSnapshot) -> Bool {
        id == other.id &&
        displayName == other.displayName &&
        compactDisplayName == other.compactDisplayName &&
        kind == other.kind &&
        primaryWindowId == other.primaryWindowId &&
        windows == other.windows &&
        spendUSD == other.spendUSD &&
        status == other.status &&
        accountsAreContentEqual(to: other.accounts)
        // Intentionally ignores `fetchedAt` to avoid reloading a timeline on
        // every successful polling heartbeat.
    }

    private func accountsAreContentEqual(to otherAccounts: [ProviderAccountSnapshot]?) -> Bool {
        switch (accounts, otherAccounts) {
        case (nil, nil):
            return true
        case let (lhs?, rhs?):
            return lhs.count == rhs.count &&
                zip(lhs, rhs).allSatisfy { $0.isContentEqual(to: $1) }
        default:
            return false
        }
    }
}

extension ProviderAccountSnapshot {
    /// Compare semantic account content while ignoring fetch heartbeats.
    func isContentEqual(to other: ProviderAccountSnapshot) -> Bool {
        id == other.id &&
        displayName == other.displayName &&
        plan == other.plan &&
        status == other.status &&
        metrics == other.metrics
    }
}
