import Foundation

/// Top-level snapshot written by the main app and consumed by the widget extension.
///
/// Schema v1 (frozen).
/// - Encoded with `JSONEncoder` and `dateEncodingStrategy = .iso8601`.
/// - `version` is bumped only on breaking shape changes; widget should refuse
///   unknown versions and fall back to a placeholder until refreshed.
///
/// Design notes:
/// - `ProviderSnapshot.usedPercent` (carried inside `windows`) is the great
///   common-denominator field across all billing models — the widget renders
///   ring/bar progress directly from it.
/// - `windows` is an array (not a flat struct) because Claude (5h+7d), Codex
///   (primary+secondary), Z.ai (token+mcp) are all multi-window.
/// - The Small widget family renders only `primaryWindowId`; Medium/Large can
///   walk `windows` if needed in later milestones.
/// - `kind = .quota` → progress bar; `kind = .usage` → big spend amount.
///   This lets the widget branch on shape without inspecting each provider's
///   internal naming.
struct WidgetSnapshot: Codable, Equatable {
    /// Schema version. Increment on breaking changes.
    let version: Int // fixed 1

    /// When this snapshot was generated by the main app.
    let snapshotAt: Date

    /// All provider snapshots in display order (sorted by usedPercent desc).
    let providers: [ProviderSnapshot]

    /// Total monthly API cost, USD and optional RMB.
    let monthlyCost: MonthlyCost?
}

/// Single provider's snapshot for widget rendering.
struct ProviderSnapshot: Codable, Equatable {
    /// Stable id matching `ProviderIdentifier.rawValue`.
    let id: String

    /// Human-readable display name.
    let displayName: String

    /// Determines rendering style: progress bar vs spend amount.
    let kind: Kind

    /// Which window in `windows` is the primary (Small family renders this).
    /// Nil if `windows` is empty.
    let primaryWindowId: String?

    /// Quota/usage windows. May be empty for usage-only providers.
    let windows: [UsageWindow]

    /// Only for `.usage` kind: cost in USD.
    let spendUSD: Double?

    /// When the provider was actually fetched (may be earlier than snapshotAt).
    let fetchedAt: Date?

    enum Kind: String, Codable, Equatable {
        /// Quota-based: progress bar driven by `usedPercent`.
        case quota
        /// Pay-as-you-go: spend amount in `spendUSD`.
        case usage
    }
}

/// Single quota window within a provider (e.g. "5h", "7d", "monthly").
struct UsageWindow: Codable, Equatable {
    /// Stable id: "5h" / "7d" / "monthly" / "token" / "mcp" / "primary" / "secondary".
    let id: String

    /// UI display label.
    let label: String

    /// 0-100+. Drives widget ring/bar rendering.
    let usedPercent: Double

    /// When this window resets.
    let resetsAt: Date?

    /// Absolute used value (quota-based only).
    let used: Int?

    /// Absolute limit value (quota-based only).
    let limit: Int?
}

/// Monthly cost summary.
struct MonthlyCost: Codable, Equatable {
    /// USD amount. Display layer formats to 2 decimals.
    let usd: Double

    /// RMB amount (optional, requires exchange rate).
    let rmb: Double?
}
